image:
  api_gateway: asia-northeast3-docker.pkg.dev/pelagic-fin-402600/artifact-registry-ci/api-main:789d094
  customers: asia-northeast3-docker.pkg.dev/pelagic-fin-402600/artifact-registry-ci/customers:f1ea3e2
  vets: asia-northeast3-docker.pkg.dev/pelagic-fin-402600/artifact-registry-ci/vets:50587ec
  visits: asia-northeast3-docker.pkg.dev/pelagic-fin-402600/artifact-registry-ci/visits:48fcc1f

# hostinfo: 10.182.103.19:3306
public_ip: petclinic
domain: www.petclinic.shop

resources:
  requests:
    cpu: "200m"
    memory: "200Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"

replicas: 3

maxReplicas: 5
minReplicas: 2